apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;
  
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri /index.html;
      
      location / {
        try_files $uri $uri/ = 404;
      }
    }
