name: 🤖 Auto assign
on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-author:
    name: PR author as an assignee
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.0
        if: env.IS_OWNER_MODE == 'true'
        with:
          repo-token: ${{ secrets.ROUTELINKBOT_TOKEN }}