name: ⚙️ Lint
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run typecheck

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
